### ISSUE TITLE
Implementazione di più contatori secTimer

### ISSUE THREAD

**Issue by fattanasio** [leomil72/secTimer#1]
Ciao leomil72,
grazie intanto per il lavoro svolto e per aver messo a disposizione questa libreria. Per il mio progetto dovrei implementare 5 contatori e ho notato che dichiarando le 5 variabili secTimer e facendole partire tutte e 5, il primo che effettua stopTimer va a stoppare tutti i timer.
E' un bug o il comportamento è normale ? Se così fosse, secondo te c'è la possibilità di gestire n contatori. 
Grazie,
Fabrizio

**Comment by leomil72** [comment]
Ciao e scusa il ritardo nella risposta. Non vedendo il tuo codice, posso intuire che tu stia utilizzando un sistema di incremento per cui tutte le variabili vengono incrementate dallo stesso loop. È normale che fermando il timer si fermi tutto, se questa è la logica di funzionamento. Una soluzione alternativa è quella di usare un array di tipo bool con tanti elementi quante sono le variabili da incrementare e poi eseguire l'incremento solo di quelle il cui elemento nell'array di bool è impostato a "true" e saltare quelle con valore "false" nella loro cella.
